In [1]:
print('Hello World')

Hello World


In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([['a', 'b', 'c', 'd', 'e'], ['f', 'g', 'h', 'i', 'j']])
print(a)
print('*'*20)
print(b)

[1 2 3 4 5]
********************
[['a' 'b' 'c' 'd' 'e']
 ['f' 'g' 'h' 'i' 'j']]


In [7]:
a = np.empty((3,4), dtype='int8')
print(a)

[[112 -45  29 -91]
 [124  85   0   0]
 [  1   0   0   0]]


In [9]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
a = np.zeros((6), dtype='int8')
print(a)

[0 0 0 0 0 0]


In [18]:
a = np.eye((4), dtype='float16')
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
a = [1,2,3]
b = np.asarray(a)
print(b)

[1 2 3]


In [21]:
a = ((1,2),(3,4))
b = np.asarray(a)
print(b)

[[1 2]
 [3 4]]


In [24]:
a = np.fromiter([1,2,3,4], dtype='int8')
b = np.fromiter('string', dtype='S50')
print(a)
print(b)

[1 2 3 4]
[b's' b't' b'r' b'i' b'n' b'g']


In [26]:
a = np.zeros(6)
b = np.arange(0,10,2)
c = a + b
print (c[4])

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [29]:
a = np.array([[0, 1, 0], [1, 0, 1]])
a += 3
b = a + 3
print(a)
print(b)
print (a[1,2] + b[1,2])

[[3 4 3]
 [4 3 4]]
[[6 7 6]
 [7 6 7]]
11


In [31]:
a = np.array([[0, 1, 2], [3, 4, 5]])
b = a.sum(axis=1)
c = a.sum(axis=0)
print (b)
print(c)

[ 3 12]
[3 5 7]
