In [5]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([['a', 'b', 'c', 'd', 'e'], ['f', 'g', 'h', 'i', 'j']])
print(a)
print('*'*20)
print(b)

[1 2 3 4 5]
********************
[['a' 'b' 'c' 'd' 'e']
 ['f' 'g' 'h' 'i' 'j']]


In [7]:
a = np.empty((3,4), dtype='int8')
print(a)

[[112 -45  29 -91]
 [124  85   0   0]
 [  1   0   0   0]]


In [9]:
# Identical Matrix
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# Create zero matrix
a = np.zeros((6), dtype='int8')
print(a)

[0 0 0 0 0 0]


In [18]:
a = np.eye((4), dtype='float16')
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
a = [1,2,3]
b = np.asarray(a)
print(b)

[1 2 3]


In [21]:
a = ((1,2),(3,4))
b = np.asarray(a)
print(b)

[[1 2]
 [3 4]]


In [24]:
a = np.fromiter([1,2,3,4], dtype='int8')
b = np.fromiter('string', dtype='S50')
print(a)
print(b)

[1 2 3 4]
[b's' b't' b'r' b'i' b'n' b'g']


In [26]:
a = np.zeros(6)
b = np.arange(0,10,2)
c = a + b
print (c[4])

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [29]:
a = np.array([[0, 1, 0], [1, 0, 1]])
a += 3
b = a + 3
print(a)
print(b)
print (a[1,2] + b[1,2])

[[3 4 3]
 [4 3 4]]
[[6 7 6]
 [7 6 7]]
11


In [4]:
a = np.array([[0, 1, 2], [3, 4, 5]])
b = a.sum(axis=1)
c = a.sum(axis=0)
print (b)
print(c)

[ 3 12]
[3 5 7]


In [15]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype='int8')
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# get dimentsion
print(b.ndim)
#get shape
print(b.shape)
#get data type
print(b.dtype)
#get size
print(b.itemsize)
# get total size
print(b.nbytes)

2
(3, 3)
int8
1
9


In [30]:
# Get specific element
print(b[2,2])
# Get specific row
print(b[0,:])

9
[1 2 3]


In [32]:
# Get specific Column
print(b[:, 2])

[3 6 9]


In [37]:
#Get speicfic row and column
print(b[1:, 1:])

[[5 6]
 [8 9]]


In [50]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)
# Get numbers in a row by applying filter
print(a[0, 1:6:2])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[2 4 6]


In [51]:
# change the specific cell value
a[1, 3] = 9
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9  9 11 12]]


In [54]:
#change the specific column values
a[:,1] = [0,0]
print(a)

[[ 1  0  3  4  5  6]
 [ 7  0  9  9 11 12]]


In [56]:
#3-d Example
a = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [60]:
# Get specific element from 3d array
print(a[1,1,0])

7


In [70]:
#Get specific row from 3d Array
print(a[0,1:,:])

[[3 4]]


In [72]:
#Get specific row from multiple sets
print(a[:, 0, :])

[[1 2]
 [5 6]]


In [74]:
#create a array using rand method
np.random.rand(4,2)

array([[0.53359959, 0.53390522],
       [0.04746593, 0.54532075],
       [0.47497324, 0.90589673],
       [0.40355453, 0.41455939]])

In [78]:
#Create a array like existing array using random method
np.random.random(a.shape)

array([[[0.41218216, 0.93406592],
        [0.87841758, 0.44902425]],

       [[0.35624442, 0.44022498],
        [0.26192041, 0.46158549]]])

In [83]:
#create a array of integer using randint method
np.random.randint(4, size=(3,3))

array([[3, 3, 0],
       [1, 3, 2],
       [1, 1, 3]])

In [100]:
#Repeat method
arr = np.array([[1,2,3], [0, 0 ,0]])
r1 = np.repeat(arr, 3, axis = 1)
print(r1)

[[1 1 1 2 2 2 3 3 3]
 [0 0 0 0 0 0 0 0 0]]


In [121]:
output_ones = np.ones([5,5])
print(output_ones)

output_zero = np.zeros([3, 3])
output_zero[1,1] = 9
print(output_zero)

output_ones[1:4,1:4] = output_zero
print(output_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
output = np.ones([5,5])