In [1]:
import numpy as np
a = np.arange(1,21, dtype='int')
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a[1,1])
print(a[2,:]) # Get last row
print(a[:2,:]) # get first two rows

5
[7 8 9]
[[1 2 3]
 [4 5 6]]


In [8]:
a=np.array([[1,2],[3,4],[5,6]])

print(a[[0,1,2],[0,1,0]])
print('==========')

print(np.array([a[0,0],a[1,1],a[2,0]]))
print('==========')

print(a[[0,0],[1,1]])
print('==========')

print(np.array([a[0,1],a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]
