In [2]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[a > 2])

[3 4 5 6 7]


In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])

# element wise addition
print(a+b)
print('==========')
print(np.add(a,b))

# element wise Substraction
print(a-b)
print('==========')
print(np.subtract(a,b))

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [9]:
import numpy as np
# initialize array for prices
prices = np.array([[40, 35, 20], [21, 48, 70]])

# Code starts here

# flatten the array
prices = prices.flatten()

# minimum price
buying_price = np.min(prices)

# index of buying price
index = list(prices).index(buying_price)

# create subset
subset = prices[index:]

# selling price
selling_price = np.max(subset)

# profit
profit = selling_price - buying_price
# display
print(profit)

# Code ends here

50


In [10]:
a = np.array([[0, 1, 2], [3, 4, 5]])
b = a.sum(axis=1)
print (b)

[ 3 12]
